apiVersion: v1
kind: Service
metadata:
  name: team-gates
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: team-gates
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-gates
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-gates
  strategy:
    resources: {}
  template:
    metadata:
      labels:
        app: team-gates
    spec:
      containers:
      - name: team-gates
        image: docker.io/dmage/team-gates
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: team-gates
spec:
  port:
    targetPort: 8080
  to:
    name: team-gates
  tls:
    termination: edge
